### ISSUE TITLE
I need access to the mediatype from decode

### ISSUE THREAD

**Issue by hildjj** [strongloop/strong-data-uri#7]
Perhaps add another API point that returns an array or object?  For example:

```js
var dataUri = require('strong-data-uri');
var uri = 'data:text/plain;base64,aGVsbG8gd29ybGQ=';
var results = dataUri.decodeWithMedia(uri);
console.log(results.data, results.media);
// Hello world text/plain
```

Alternately, and simpler, just a mediatype function that runs the regex:

```js
var dataUri = require('strong-data-uri');
var uri = 'data:text/plain;base64,aGVsbG8gd29ybGQ=';
var media = dataUri.mediatype(uri);
console.log(results.media);
// text/plain
```

**Comment by bajtos** [comment]
How about this variant?

```js
var dataUri = require('strong-data-uri');
var uri = 'data:text/plain;base64,aGVsbG8gd29ybGQ=';
var result = dataUri.decode(uri);
console.log(result.mediaType)
// text/plain
```

Can you submit a pull request please?

**Comment by hildjj** [comment]
Is result still a string there?  If so, that's just fine.  If not, it's a breaking API change, which would be sub-optimal.

**Comment by bajtos** [comment]
> Is result still a string there? If so, that's just fine. If not, it's a breaking API change, which would be sub-optimal.

The result is Buffer IIRC, but that's not important. The type will remain the same (no breaking change), we will just add some new properties on the instance returned.

```js
var result;
if (/;base64$/.test(header)) {
  result = new Buffer(body, 'base64');
} else {
  result = new Buffer(decodeURIComponent(body), 'ascii');
}
result.mediaType = // parse media type
return result;
```

**Comment by hildjj** [comment]
Yes, that will work really well.  Do you need a PR from me? Looks like you're almost there except for the tests.

**Comment by bajtos** [comment]
Yes please, PR will be awesome. I am afraid I don't have time to work on this now :(
